# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('sentence', models.IntegerField()),
                ('quote', models.TextField()),
            ],
            options={
                'ordering': ('chapter', 'verse', 'sentence'),
            },
        ),
        migrations.CreateModel(
            name='PrayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prayer', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
