# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s4j', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
