# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s4j', '0002_biblemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldmodel',
            options={'ordering': ('book', 'chapter', 'verse')},
        ),
        migrations.RenameField(
            model_name='fieldmodel',
            old_name='sentence',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='fieldmodel',
            old_name='quote',
            new_name='passage',
        ),
    ]
