# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s4j', '0005_auto_20171013_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genremodel',
            name='genre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genremodel',
            name='genreNumber',
            field=models.TextField(),
        ),
    ]
