# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s4j', '0006_auto_20171013_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genremodel',
            name='genreNumber',
            field=models.IntegerField(),
        ),
    ]
