# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s4j', '0008_auto_20171014_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='genre',
            field=models.IntegerField(),
        ),
    ]
