# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s4j', '0010_auto_20171014_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmodel',
            name='bible',
            field=models.TextField(default=b'we'),
        ),
    ]
