# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s4j', '0011_fieldmodel_bible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldmodel',
            old_name='bible',
            new_name='bibleName',
        ),
    ]
