# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s4j', '0012_auto_20171014_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BibleModel',
        ),
    ]
