# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s4j', '0013_delete_biblemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
            ],
        ),
    ]
