# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s4j', '0014_biblemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmodel',
            name='bibleName',
            field=models.TextField(default=b'boo hoo I am not set'),
        ),
    ]
